### ISSUE TITLE
[PT2.6] Implement >= 80% Aten ops support

### ISSUE THREAD

**Issue by riverliuintel** [intel/torch-xpu-ops#1001]
### 🚀 The feature, motivation and pitch

PyTorch 2.6 Aten ops coverage support requirement >= 80% and pin to stock PyTorch repo before feature freeze. It requires to pass 100% UT on both Linux and Windows. The platform needs to cover PVC and client GPU.

**Comment by xytintel** [comment]
Goal meet at https://github.com/intel/torch-xpu-ops/commit/804a03b76e6b1270327f3f6ddbe58b6ffba5d30e (86.4% of CUDA)
