### ISSUE TITLE
[PT2.6] Pip install Torch and all PyPI dependency

### ISSUE THREAD

**Issue by riverliuintel** [intel/torch-xpu-ops#1007]
### 🚀 The feature, motivation and pitch

There are two scenarios for PyTorch XPU release. 1) pip install torch wheels in one host machine without GPU driver installed. Import torch will fallback to CPU. 2) install driver and pip install torch for AI workload run on GPU. 3) install driver, install deep-learning-essential bundle and pip install torch can work well on GPU. 4)  install driver, install deep-learning-essential bundle and source build pyTorch.

OS: Linux, Windows

**Comment by chuanqi129** [comment]
Tracked in https://github.com/pytorch/pytorch/issues/139722

**Comment by riverliuintel** [comment]
done in PyTorch main branch.
