### ISSUE TITLE
index_select_xpu not implemented for 'Float8_e4m3fn'

### ISSUE THREAD

**Issue by LuFinch** [intel/torch-xpu-ops#1053]
### 🐛 Describe the bug

index_select_xpu cause an IPEX UT fail.  In IPEX2.5, we override this Ops with IPEX implementation to make this UT pass. 

ipex/tests/gpu/example/test_fp8_index_select.py::TestTorchMethod::test_index_select 

'index_select_xpu' not implemented for 'Float8_e4m3fn'

### Versions

..

**Comment by daisyden** [comment]
created a PR for index_select, https://github.com/intel/torch-xpu-ops/pull/1081/files

**Comment by daisyden** [comment]
merged.
