### ISSUE TITLE
[E2E_baseline] Torchbench some training model have "Don't know how to reduce" crash

### ISSUE THREAD

**Issue by chuanqi129** [intel/torch-xpu-ops#111]
### 🐛 Describe the bug

There are some models training crashed on `NotImplementedError:("Don't know how to reduce", <>)`

| Model | Precision | Failure | Mode | Fail_reason |
| -- | -- | -- | -- | --|
| doctr_det_predictor | fp32/bf16/fp16 | eager_fail_to_run |  training | `NotImplementedError: ("Don't know how to   reduce", <class 'numpy.ndarray'>)` |
| doctr_reco_predictor | fp32/bf16/fp16 | eager_fail_to_run | training | `NotImplementedError: ("Don't know how to reduce", <class   'str'>)` |
detectron2_maskrcnn | fp32 | eager_fail_to_run |  training | `NotImplementedError: ("Don't know how to   reduce", <class 'detectron2.structures.instances.Instances'>)`
detectron2_maskrcnn_r_50_c4 | fp32 | eager_fail_to_run |  training | `NotImplementedError: ("Don't know how to reduce", <class   'detectron2.structures.instances.Instances'>)`

### Versions

Pytorch: `git clone -b e2e-baseline https://github.com/etaf/pytorch-inductor-xpu pytorch`
Test script: [`inductor_xpu_test.sh`](https://github.com/intel/torch-xpu-ops/blob/main/.github/scripts/inductor_xpu_test.sh)

**Comment by retonym** [comment]
These issues also happen on A100 platform,  not related to xpu implementation

**Comment by chuanqi129** [comment]
Close it as we have refreshed baseline
