### ISSUE TITLE
SSD-MobileNet got fail(AttributeError: module 'torch.xpu' has no attribute 'locations_to_boxes')

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1135]
### 🚀 The feature, motivation and pitch

Run ssd-mobilenetv1 on LNL Windows with https://github.com/intel-innersource/frameworks.ai.pytorch.gpu-models/SSD-MobileNetv1 on stock PyTorch got error 
```
fail(AttributeError: module 'torch.xpu' has no attribute 'locations_to_boxes'). 
```
This is because the model used an ipex customized op at [link](https://github.com/intel-innersource/frameworks.ai.pytorch.gpu-models/blob/daisyden/stock_pt/SSD-MobileNetv1/vision/ssd/ssd.py#L94). Do we need to support it or use an official version on ssd-mobilenet in torch_vision?

OneAPI 2025.0.0+compiler 2025.0.1
PyTorch wheel is install on IPEX_2.5.10+xpu/RC1

**Comment by Stonepia** [comment]
Since we are going to use OOB model scripts instead of the IPEX scripts, we will close this issue.
