### ISSUE TITLE
set_fp32_math_mode() is not supported on torch.xpu.

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1136]
### 🚀 The feature, motivation and pitch

IPEX model resnet50 main.py called torch.xpu.set_fp32_math_mode(torch.xpu.FP32MathMode.FP32) but stock pytorch does not have the API. We could also need to understand the impact of this setting to resnet50.

**Comment by Stonepia** [comment]
This should be related to the IPEX-specific API, since we discussed to use OOB model scripts rather than IPEX scripts, we will close this issue.
