### ISSUE TITLE
[E2E_baseline] Torchbench training accuracy test some models have RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by chuanqi129** [intel/torch-xpu-ops#114]
### 🐛 Describe the bug

Below models training crashed with `RuntimeError: element   0 of tensors does not require grad and does not have a grad_fn`
Model | Precision
-- | --
cm3leon_generate | fp32/bf16/fp16
DALLE2_pytorch | fp32/bf16/fp16
hf_T5_generate | fp32/bf16/fp16
maml | fp32/bf16/fp16
pyhpc_equation_of_state | fp32/bf16/fp16
pyhpc_isoneutral_mixing | fp32/bf16/fp16
sam | fp32/bf16/fp16
sam_fast | fp32

### Versions

Pytorch: `git clone -b e2e-baseline https://github.com/etaf/pytorch-inductor-xpu pytorch`
Test script: [`inductor_xpu_test.sh`](https://github.com/intel/torch-xpu-ops/blob/main/.github/scripts/inductor_xpu_test.sh)

**Comment by chuanqi129** [comment]
`DALLE2_pytorch` and `sam` float16 cuda has same failure message

**Comment by retonym** [comment]
These issues also happen on A100 platform, not related to xpu implementation

**Comment by chuanqi129** [comment]
Close it as we have refreshed baseline

**Comment by bjarzemb** [comment]
I have this issue in latest Weekly for hf_T5_generate.

@mengfei25 can you check CUDA result for this model?
