### ISSUE TITLE
[E2E_baseline] Torchbench detectron2 series models accuracy test with RuntimeError: dets should have the same type as scores

### ISSUE THREAD

**Issue by chuanqi129** [intel/torch-xpu-ops#117]
### 🐛 Describe the bug

Those `detectron2` series models accuracy crash with `RuntimeError: dets should have the same type as scores`
Model | Precision | Mode
-- | -- | --
detectron2_fasterrcnn_r_101_c4 | bf16/fp16 | inference
detectron2_fasterrcnn_r_101_dc5 | bf16/fp16 | inference
detectron2_fasterrcnn_r_101_fpn | bf16/fp16 | inference
detectron2_fasterrcnn_r_50_c4 | bf16/fp16 | inference
detectron2_fasterrcnn_r_50_dc5 | bf16/fp16 | inference
detectron2_fasterrcnn_r_50_fpn | bf16/fp16 | inference
detectron2_maskrcnn | bf16/fp16 | inference
detectron2_maskrcnn_r_101_c4 | bf16/fp16 | inference
detectron2_maskrcnn_r_101_fpn | bf16/fp16 | inference
detectron2_maskrcnn_r_50_c4 | bf16/fp16 | inference
detectron2_maskrcnn_r_50_fpn | bf16/fp16 | inference
detectron2_maskrcnn | bf16/fp16 | training
detectron2_maskrcnn_r_50_c4 | bf16/fp16 | training

### Versions

Pytorch: `git clone -b e2e-baseline https://github.com/etaf/pytorch-inductor-xpu pytorch`
Test script: [`inductor_xpu_test.sh`](https://github.com/intel/torch-xpu-ops/blob/main/.github/scripts/inductor_xpu_test.sh)

**Comment by chuanqi129** [comment]
Close it as we have refreshed baseline

**Comment by anmyachev** [comment]
I am still seeing this problem message in `WARNING:common:current_device=xpu; error:dets should have the same type as scores`.

I have a fix for it in https://github.com/facebookresearch/detectron2/pull/5479 but I doubt that it will be merged, since the repository is not very active.
