### ISSUE TITLE
Please fix mixed device types in input Tensors of torch.lerp on release 2.6

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#1200]
### 🐛 Describe the bug

Release 2.6 got failures because the cpu "weight" , https://github.com/pytorch/pytorch/blob/release/2.6/test/test_binary_ufuncs.py#L3473, we could need to cherry-pick the lerp fixing in this PR to 2.6 release branch, https://github.com/intel/torch-xpu-ops/pull/1144.

FAILED test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_lerp_xpu_complex128 - RuntimeError: iter.device(arg).is_xpu() INTERNAL ASSERT FAILED
--
FAILED test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_lerp_xpu_complex64 - RuntimeError: iter.device(arg).is_xpu() INTERNAL ASSERT FAILED
FAILED test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_lerp_xpu_float32 - RuntimeError: iter.device(arg).is_xpu() INTERNAL ASSERT FAILED
FAILED test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_lerp_xpu_float64 - RuntimeError: iter.device(arg).is_xpu() INTERNAL ASSERT FAILED

### Versions

2.6

**Comment by xytintel** [comment]
[Rel](https://github.com/pytorch/pytorch/commit/a52d9f6f4c9c839b0312fbe02925b38cd1f40758#diff-fef2ee1307d8d82cd8ccfa4188ab3808635370a8c3b3e579c277cdfe26af18a2)
