### ISSUE TITLE
Enable HostCachingAlloctor

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#125]
### 🚀 The feature, motivation and pitch

HostCachingAlloctor provides pin memory for H2D and D2H copy. Some kernels require the alloctor, E.g. copy, cat...

### Alternatives

Using system memory + synchronization to ensure functionality. But it will hurt performance.

**Comment by fengyuan14** [comment]
WA for Copy.
https://github.com/intel/torch-xpu-ops/pull/127

**Comment by fengyuan14** [comment]
XPU HostCachingAlloctor PR of PyTorch,
https://github.com/pytorch/pytorch/pull/123080

**Comment by riverliuintel** [comment]
Done.
