### ISSUE TITLE
need matmul fp64 support from oneDNN 

### ISSUE THREAD

**Issue by AlienLiang23** [intel/torch-xpu-ops#156]
### 🐛 Describe the bug

test_ops.py::TestCommonXPU::test_dtypes_nn_functional_scaled_dot_product_attention_xpu FAILED
![image](https://github.com/intel/torch-xpu-ops/assets/51150101/a7f7842a-79a0-4f1e-85a5-177d1c9d6ddd)

Skip this case to WA this issue.

### Versions

yongliang/sdpa-math 
[8a35768](https://github.com/intel/torch-xpu-ops/pull/154/commits/8a35768049e31c239772bceaee3a2f7a39bf9b7c)

**Comment by chuanqi129** [comment]
@ZhiweiYan-96 please double check whether we can close this issue

**Comment by daisyden** [comment]
duplicated with https://github.com/intel/torch-xpu-ops/issues/253, close it
