### ISSUE TITLE
Complement XPU implementation for operators supported by explicit CPU fallback implementation.

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#162]
### 🚀 The feature, motivation and pitch

For some priority gaps, we implement some operators with explicit CPU fallback. We will add XPU implementation according to priority requirements.

- [ ] nonzero  // update xpu pin 2.5
- [x] tril  // SDP math
- [x] softmax  // SDP math
- [x] softmax_backward  // SDP math
- [ ] fft  // MKL 2.5

**Comment by riverliuintel** [comment]
Yifeng works on fft//MKL, Chunhuan works on others.

**Comment by fengyuan14** [comment]
HF .compile and HF eager requirements are done. Nonzero and fft will be tracked by following operators development task. Close the issue.
