### ISSUE TITLE
[TODO][Inductor UT dependency] Need to implement torch.xpu.memory_allocated()

### ISSUE THREAD

**Issue by etaf** [intel/torch-xpu-ops#163]
### 🚀 The feature, motivation and pitch

@guangyey  can you take this requirement?

**Comment by riverliuintel** [comment]
@guangyey  check this with Xinan.

**Comment by chuanqi129** [comment]
@guangyey please double check whether we can close this issue or not

**Comment by guangyey** [comment]
see https://github.com/pytorch/pytorch/pull/129919

**Comment by chuanqi129** [comment]
Seems we can close this issue now cause https://github.com/pytorch/pytorch/pull/129919 got merged.
