### ISSUE TITLE
Add common device check at operator level.

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#166]
### 🚀 The feature, motivation and pitch

Since we use different ATen dispatch stub code gen script, we have to add checks manually to align with stock CUDA behavior. So far, these checks are not critical,
1. Common device check. Informative error at runtime.
2. Device guard. We set device guard on demand at kernel level.
![image](https://github.com/intel/torch-xpu-ops/assets/28250760/a70d9361-e77b-4fce-b013-341ac7e994e1)

**Comment by chuanqi129** [comment]
According to the latest evaluation, we don't need it
