### ISSUE TITLE
Evaluate aten::concat performance

### ISSUE THREAD

**Issue by xytintel** [intel/torch-xpu-ops#198]
### 🚀 The feature, motivation and pitch

![image](https://github.com/intel/torch-xpu-ops/assets/86954368/95cc4f49-0134-48cb-8d97-5790abe914f7)

1. Find the most suitable parameter CAT_ARRAY_BATCH_SIZE.
2. Compare performance with IPEX implementation

**Comment by riverliuintel** [comment]
Duplicated. Closed
