### ISSUE TITLE
[TODO][Inductor UT dependency] NotImplementedError: elapsed_time is not supported by XPUEvent

### ISSUE THREAD

**Issue by etaf** [intel/torch-xpu-ops#228]
### 🚀 The feature, motivation and pitch

NotImplementedError: elapsed_time is not supported by XPUEvent

**Comment by chuanqi129** [comment]
@guangyey could you please update the status for this issue?

**Comment by guangyey** [comment]
depends on 2025.0

**Comment by riverliuintel** [comment]
PR submitted: https://github.com/pytorch/pytorch/pull/140873

**Comment by riverliuintel** [comment]
done on main branch.
