### ISSUE TITLE
Provide a way to debug explicit CPU fallback

### ISSUE THREAD

**Issue by dvrogozh** [intel/torch-xpu-ops#262]
@fengyuan14 - The commit https://github.com/intel/torch-xpu-ops/commit/5bf9e0cc768f7a3b13d829118683275f324399f1 muted debug logs of "explicit" CPU fallbacks. This complicated debug for 3d party contributors trying to evaluate XPU backend capabilities - now I am forced to revert noted commit to understand which operations are not currently implemented by XPU. Please:

1. Explain what "explicit CPU fallback" means - this seems to be internal to xpu team classification which is unclear and confusing
2. Extend `PYTORCH_DEBUG_XPU_FALLBACK=1` to track any CPU fallback happening in XPU backend. Note: I am fine if "explicit" fallback will be muted by default, but I really need a way to be able to track it.

```
commit 5bf9e0cc768f7a3b13d829118683275f324399f1 (origin/meng_max_2d)
Author: Feng Yuan <feng1.yuan@intel.com>
Date:   Mon Apr 29 13:05:51 2024 +0800

    Register operator's implementation lazily. (#177)

    1. Avoid dangling operator's implementation (m.impl(torchvision::nms) is
    ahead of `import torchvision` sometime)
    2. Mute debug log of explicit CPU fallback.
    3. Add torchvision.roi_align/_roi_align_backward example case
```

CC: @jgong5 @mingfeima @XiaobingSuper @ashokei @jingxu10 @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by dvrogozh** [comment]
Also filed https://github.com/pytorch/pytorch/issues/126488 for visibility at pytorch level.

**Comment by fengyuan14** [comment]
Thanks for your feedback. Replied in https://github.com/pytorch/pytorch/issues/126488.
