### ISSUE TITLE
XPU Tensor fails in copy-on-write cases

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#281]
### 🚀 The feature, motivation and pitch

To support or make XPU Tensor compatible with copy-on-write feature.

Case: TestCompositeCompliance::test_cow_input

AssertionError: False is not true : Keyword argument 'output grad 0' during backward call unexpectedly materializes. Either set `supports_cow_input_no_materialize_backward=False` in this operation's OpInfo, add the arg to the OpInfo's `allow_cow_input_materialize_backward` list, or change the implementation to avoid materialization.

**Comment by chuanqi129** [comment]
Need to discuss with @EikanWang

**Comment by chunhuanMeng** [comment]
Three cases left:
    "test_cow_input_addr_xpu_float32", because onednn addmv
    "test_cow_input_cdist_xpu_float32", because onednn mm
    "test_cow_input_nn_functional_multi_head_attention_forward_xpu_float32",because onednn addmm

**Comment by xytintel** [comment]
PR merged and all the relevant UTs passed.
