### ISSUE TITLE
CPU/CUDA bias code in aten::mode_out

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#327]
### 🚀 The feature, motivation and pitch

Hard-coded CPU/CUDA bias in aten::mode_out. To upstream to make the operator device compatible.

**Comment by chuanqi129** [comment]
475     # CPU/CUDA bias code in aten::mode_out
1476     # https://github.com/intel/torch-xpu-ops/issues/327
1477     # RuntimeError: mode only supports CPU AND CUDA device type, got: xpu
1478     "test_dim_reduction",
1479     "test_mode",
1480     "test_dim_reduction_fns_fn_name_mode",

**Comment by fengyuan14** [comment]
The PR is merged. https://github.com/pytorch/pytorch/pull/137575
