### ISSUE TITLE
Integer div result with wrong data type(shoule be float but got int).

### ISSUE THREAD

**Issue by etaf** [intel/torch-xpu-ops#33]
Integer div result with wrong data type(shoule be float but got int).

torch-xpu-ops commit: d19b7f6e2e3c770d9c26b8f5b6ea299cae66bb2d
Reproduce cases: 
diff --git a/test/python/examples/test_binary.py b/test/python/examples/test_binary.py
index 4768a59..352644a 100644
--- a/test/python/examples/test_binary.py
+++ b/test/python/examples/test_binary.py
@@ -41,3 +51,20 @@ class TestSimpleBinary(TestCase):
         c_xpu = a_xpu / b_xpu
         c_cpu = a_cpu / b_cpu
         self.assertEqual(c_cpu, c_xpu.to(cpu_device))
+
+    def test_div_dtype(self, dtype=torch.float):
+        a_cpu = torch.randint(2, 3, [8, 8])
+        b_cpu = torch.randint(2, 3, [8, 8])
+
+        a_xpu = a_cpu.to(xpu_device)
+        b_xpu = b_cpu.to(xpu_device)
+        c_xpu = a_xpu / b_xpu
+        c_cpu = a_cpu / b_cpu
+        self.assertEqual(c_cpu.dtype, c_xpu.dtype)
+        self.assertEqual(c_cpu, c_xpu.to(cpu_device))

**Comment by fengyuan14** [comment]
https://github.com/intel/torch-xpu-ops/pull/34
