### ISSUE TITLE
NotImplementedError: The operator 'aten::_foreach_mul_.Scalar' is not currently implemented for the XPU device.

### ISSUE THREAD

**Issue by ZhaoqiongZ** [intel/torch-xpu-ops#358]
### 🚀 The feature, motivation and pitch

Train with a simple resnet50 model on XPU and found _foreach_mul_.Scalar not implemented
Fallback to CPU can help on running the training process, but will have a performance implications.

**Comment by riverliuintel** [comment]
have a check whether this op is included in our plan before PT2.5.

**Comment by fengyuan14** [comment]
Not included.

**Comment by dvrogozh** [comment]
This is one of the operators which affect Huggingface examples. See https://github.com/huggingface/transformers/issues/31237#issuecomment-2148067845.

**Comment by fengyuan14** [comment]
https://github.com/intel/torch-xpu-ops/pull/376

**Comment by chuanqi129** [comment]
@fengyuan14 if this issue have been implemented, please help to close it

**Comment by chuanqi129** [comment]
@dvrogozh please double check whether we can close this issue, if not please feel free to reopen
