### ISSUE TITLE
[To Enable] Enable test_meta

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#363]
### 🚀 The feature, motivation and pitch
Meta support.

According to the case report of IPEX, some XPU operators fail in test_meta. Will enable the case and have a fully functionality checking to see what we missed.

**Comment by yuchengliu1** [comment]
enable in https://github.com/intel/torch-xpu-ops/pull/571

**Comment by daisyden** [comment]
@yuchengliu1 could you please help to triage the issues in test_meta? You can sync with IPEX team about the known issues.
