### ISSUE TITLE
UT got failed with latest driver 803.58

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#367]
### 🐛 Describe the bug

Please refer to https://github.com/mengfei25/torch-xpu-ops/actions/runs/9346713959/job/25722148645, there are 11 failed.
Finegrain: 1 failed
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/fin_grain/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu__refs_rsub_xpu_float16
XPU OP UT: 10 failed
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_noncontiguous_samples_pca_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_noncontiguous_samples_svd_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_variant_consistency_eager_pca_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_variant_consistency_eager_svd_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestMathBitsXPU.test_conj_view_pca_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestMathBitsXPU.test_conj_view_svd_lowrank_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_to_nn_GRUCell_swap_True_set_grad_False_xpu_float32
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_to_nn_GRU_eval_mode_swap_True_set_grad_False_xpu_float32
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_to_nn_GRU_train_mode_swap_True_set_grad_False_xpu_float32
PYTORCH_TEST_WITH_SLOW=1 python test_autograd_xpu.py -k TestAutograd.test_multi_grad_all_hooks

### Versions

PyTorch: 2024-06-03 nightly release
Torch-xpu-ops: release/2.4 (bd76ae2a5a233ae57911c1de81322dcea19493c1)
Driver: 803.58
Bundle: 0.5.0
Device: PVC1024 on ubuntu 22.04

**Comment by daisyden** [comment]
Mengfei vrified "PYTORCH_TEST_WITH_SLOW=1 python test/xpu/fin_grain/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu__refs_rsub_xpu_float16 " is machine specific issue. I will have a check.

**Comment by mengfei25** [comment]
Do we need check it on 803.58 or latest LTS is enough?

**Comment by mengfei25** [comment]
Fine on 803.61
