### ISSUE TITLE
xpu: aten::nll_loss2d_* not implemented for XPU backend affecting Huggingface examples

### ISSUE THREAD

**Issue by dvrogozh** [intel/torch-xpu-ops#372]
See also: https://github.com/pytorch/pytorch/issues/127937

These `nil_loss2d_*` ops are not currently implemented for XPU backend and are not marked for "explicit" CPU fallback. This means that running model with any of these ops will fail at runtime by default (with not implemented error) and will require to set `PYTORCH_DEBUG_XPU_FALLBACK=1`.

- [x] `aten::nll_loss2d_backward`
- [x] `aten::nll_loss2d_forward`

This issue affects XPU enabling for Huggingface - https://github.com/huggingface/transformers/issues/31237#issuecomment-2148067845. See table in this comment for the list of affected examples and models.

**Comment by chuanqi129** [comment]
Hi @dvrogozh please double check whether we can close this issue https://github.com/intel/torch-xpu-ops/pull/530

**Comment by dvrogozh** [comment]
> Hi @dvrogozh please double check whether we can close this issue https://github.com/intel/torch-xpu-ops/pull/530

Yes, works on my side now. Corresponding HF tests are passing.
