### ISSUE TITLE
Embedding bag fine gran case fails due to unimplemented operator `aten::embedding_renorm_`

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#380]
### 🚀 The feature, motivation and pitch

To retrieve the fine gran case when embedding_renorm_ added.

**Comment by chuanqi129** [comment]
@fengyuan14 please help to reassign this issue if it not completed yet

**Comment by huaiyuzh** [comment]
This issue is the same as https://github.com/intel/torch-xpu-ops/issues/636. Suggest closing this one.

**Comment by fengyuan14** [comment]
https://github.com/intel/torch-xpu-ops/pull/885

**Comment by chunhuanMeng** [comment]
cases related to `embedding bag` all passed, we can close this issue.

**Comment by xytintel** [comment]
Implemented in https://github.com/intel/torch-xpu-ops/pull/885
