### ISSUE TITLE
Fail in test_autocast_xpu::TestAutocastGPU

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#384]
### 🐛 Describe the bug

Failure in pre-ci,
https://github.com/intel/torch-xpu-ops/actions/runs/9413187922/job/25929444890?pr=366
test_autocast_xpu.py::TestAutocastGPU::test_cast_cache_is_global FAILED  [ 25%]

Guilty commit,
https://github.com/pytorch/pytorch/pull/127741

### Versions

Latest PyTorch.

**Comment by guangyey** [comment]
fixed in https://github.com/pytorch/pytorch/pull/128383. Close this ticket.
