### ISSUE TITLE
[To Evaluate] Skipped cases due to lack of XPU implementation of aten::_sparse_coo_tensor_with_dims_and_tensors

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#386]
### 🚀 The feature, motivation and pitch

The operator has been implemented in torch-xpu-ops. Need reevaluate the skipped cases (in run_test_with_skip.py).
https://github.com/intel/torch-xpu-ops/pull/371

**Comment by yuchengliu1** [comment]
Retested and got a new Runtime error as below
https://github.com/intel/torch-xpu-ops/pull/371#issuecomment-2149389741

**Comment by yuchengliu1** [comment]
https://github.com/intel/torch-xpu-ops/pull/391

**Comment by chuanqi129** [comment]
@yuchengliu1 please check whether we have duplicated issue

**Comment by daisyden** [comment]
Track the issue in https://github.com/intel/torch-xpu-ops/issues/357
