### ISSUE TITLE
[E2E][Triton] TIMM model pnasnet5large accuracy regression.

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#408]
### 🐛 Describe the bug

Skip the model in pre-ci. Please retrieve the case, if triton gets fixing.
https://github.com/intel/intel-xpu-backend-for-triton/issues/1353

### Versions

Latest main.

**Comment by etaf** [comment]
This issue have been fixed in latest triton main branch.  we'll update triton to resolve this issue.

**Comment by etaf** [comment]
Please keep this open issue, we've not updated triton.

**Comment by chuanqi129** [comment]
@etaf please help to double check whether we can close it

**Comment by retonym** [comment]
@etaf  could we close this issue now.
