### ISSUE TITLE
[TEST] Could not skip fine-gran case correctly

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#412]
### 🐛 Describe the bug

We have improved and aligned the condition of device choice in test infrastructure. https://github.com/pytorch/pytorch/pull/124147. After that, we cannot correctly skip fine-gran cases.
New failure in fine-gran cases, test_compare_cpu_abs_xpu_bool, which was skipped before the commit above.

### Versions

Latest PyTorch

**Comment by chuanqi129** [comment]
@daisyden please help to double check whether this issue still exist

**Comment by daisyden** [comment]
The case is skipped in latest code
