### ISSUE TITLE
[E2E]TorchBench Bf16 yolov3 fails

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#414]
### 🐛 Describe the bug
https://github.com/intel/torch-xpu-ops/actions/runs/9542385293/job/26297127499?pr=407
xpu,yolov3,4,fail_accuracy,533,2,6,4,0,0,2
num_total: 16
num_passed: 15
num_failed: 1
pass_rate: 93.75%

### Versions

Latest PyTorch main and torch-xpu-ops main

**Comment by fengyuan14** [comment]
Skipped the model in pre-ci. Please retrieve it once the bug is fixed.

**Comment by etaf** [comment]
This bug is introduced by https://github.com/pytorch/pytorch/pull/128269, I'll continue to investigate.

**Comment by etaf** [comment]
Can not reproduce anymore after apply fp64 path( torch-xpu-ops/.github/scripts/apply_torch_pr.py).

**Comment by chuanqi129** [comment]
@mengfei25 please help to double check it. If this issue have been fixed, please close it

**Comment by etaf** [comment]
Please keep this open issue, we've not updated triton.

**Comment by chuanqi129** [comment]
@etaf please help to double check whether we can close it

**Comment by etaf** [comment]
> @etaf please help to double check whether we can close it

Yes, the model can pass accuracy test on currently pinned triton now. Please update the "total test num".

**Comment by retonym** [comment]
@etaf could we close this issue now.

**Comment by etaf** [comment]
Yes, the model can pass accuracy test on currently pinned triton now. Please update the "total test num".
