### ISSUE TITLE
upsample_bilinear2d fast kernel path support

### ISSUE THREAD

**Issue by majing921201** [intel/torch-xpu-ops#427]
CUDA add one kernel for performance optimization to support partial channel last case. 
https://github.com/pytorch/pytorch/blob/df85f34a14dd30f784418624b05bd52b12ab8b0b/aten/src/ATen/native/cuda/UpSampleBilinear2d.cu#L290

performance enhancement is not in 2.5 scope

**Comment by dvrogozh** [comment]
Is this issue to track something beyond what's being currently done in https://github.com/intel/torch-xpu-ops/pull/422?

**Comment by chuanqi129** [comment]
@majing921201 please help to double check it. If this issue have been done, please close it

**Comment by chuanqi129** [comment]
Need align with cuda to do the channel last optimization for performance

**Comment by majing921201** [comment]
https://github.com/intel/torch-xpu-ops/pull/950

**Comment by xytintel** [comment]
Merged
