### ISSUE TITLE
Sigmoid op didn't be supported with complex32 which didn't align with CUDA behavior.

### ISSUE THREAD

**Issue by PenghuiCheng** [intel/torch-xpu-ops#435]
### 🐛 Describe the bug

log:
RuntimeError: "sigmoid_xpu" not implemented for 'ComplexHalf'
cases:
TestCommonXPU.test_complex_half_reference_testing_sigmoid_xpu_complex32
TestCommonXPU.test_complex_half_reference_testing_sigmoid_xpu_complex32
TestCommonXPU.test_dtypes_sigmoid_xpu
 TestCommonXPU.test_python_ref__refs_sigmoid_xpu_complex32
 TestCommonXPU.test_python_ref_errors__refs_where_xpu
 TestCommonXPU.test_python_ref_executor__refs_sigmoid_executor_aten_xpu_complex32
TestCommonXPU.test_python_ref_torch_fallback__refs_sigmoid_xpu_complex32

### Versions

latest version

**Comment by fengyuan14** [comment]
https://github.com/intel/torch-xpu-ops/pull/429

**Comment by fengyuan14** [comment]
Please verify, the issue is fixed. And cases are retrieved.

**Comment by chuanqi129** [comment]
@PenghuiCheng please double check it. If it has been fixed, please close this issue

**Comment by chuanqi129** [comment]
Confirmed with @fengyuan14, we can close this issue
