### ISSUE TITLE
Different behavior in adaptive average pooling as CPU and CUDA when output_size == 1

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#523]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/blob/76259ebfdd83389eeb5735e76f66fd2ad84a9671/aten/src/ATen/native/AdaptiveAveragePooling.cpp#L120
When output_size == 1, CPU and CUDA are using reduce mean, but we are using adaptive_avg_pool. The story is we preferred oneDNN implementation before.
The issue is recorded to evaluate whether the difference should be kept.

The current implementation is to register wrapper variant `aten::adaptive_avg_pool2d` to retrieve the logic for XPU.
https://github.com/intel/torch-xpu-ops/pull/445/files#diff-c9c95053eb36049540db8fe17969d81b66fb3ec6ef753deaf0219eb7b13c9998R39-R67

**Comment by fengyuan14** [comment]
Without the logic (mean for output_size == 1), a model in TorchBench crashes due to lack of deterministic impl in adaptive avg pool2d.

**Comment by fengyuan14** [comment]
Please let me clean the label, since it is not a must and needs a further discussion. It is block format related.

**Comment by fengyuan14** [comment]
The feature is supported in torch-xpu-ops. The issue says if we should go in-tree, but which breaks block format usage.

**Comment by fengyuan14** [comment]
PyTorch WA of XPU is removed by Yunfei. We should align PyTorch CUDA/CPU implementation to follow the calling logic of the composite operator, removing the override in torch-xpu-ops.

**Comment by fengyuan14** [comment]
@CuiYifeng Please take a look.

**Comment by retonym** [comment]
@CuiYifeng  what is the latest status for this issue, does it target to PT 2.6

**Comment by CuiYifeng** [comment]
@retonym The behavior of XPU `adaptive_avg_pool{2d/3d}` has been aligned to CUDA/CPU after [pytorch#132217](https://github.com/pytorch/pytorch/pull/132217) is merged. Our WA for `output_size == 1` will not be executed. The redundant implementation in torch-xpu-ops has been removed by #851.
