### ISSUE TITLE
Probable precision error of Inductor on TorchBench/timm_efficientnet ampbf16 training

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#528]
### 🐛 Describe the bug

After enabling XPU adaptive pooling 2d, accuracy of Eager is better than Inductor (before that, CPU fallback == Inductor), and the gap could not be accepted by default Dynamo benchmark tolerance.
```
xpu  train timm_efficientnet                  
E0702 17:27:03.278000 140425655064384 torch/_dynamo/utils.py:1470] RMSE (res-fp64): 0.00068, (ref-fp64): 0.00004 and shape=torch.Size([1152]). res.dtype: torch.bfloat16, multiplier: 3.000000, tol: 0.001000
E0702 17:27:03.279000 140425655064384 torch/_dynamo/utils.py:1384] Accuracy failed for key name blocks.6.0.bn1.bias.grad
fail_accuracy
```
https://github.com/intel/torch-xpu-ops/pull/445
Loose the tolerance for the model temporarily.

### Versions

https://github.com/intel/torch-xpu-ops/pull/445

**Comment by chuanqi129** [comment]
@retonym please help to reassign this issue

**Comment by chuanqi129** [comment]
@retonym please check cuda RSME

**Comment by retonym** [comment]
fix pr: https://github.com/intel/torch-xpu-ops/pull/668

**Comment by chuanqi129** [comment]
@retonym due to the fix PR merged, can we mark this issue as done?

**Comment by retonym** [comment]
verified pass with latest code
