### ISSUE TITLE
Implement aten::_embedding_bag_backward

### ISSUE THREAD

**Issue by chunhuanMeng** [intel/torch-xpu-ops#536]
### 🚀 The feature, motivation and pitch

retrieve this case when this op has been implemented , 
"test_backward_nn_functional_embedding_bag_xpu_float32"

**Comment by chuanqi129** [comment]
@fengyuan14 do we plan add this op before pytorch 2.5 branch out? If so, please help to assign owner for it

**Comment by fengyuan14** [comment]
Checked registration in latest PyTorch. It is now a required registration. The change occurs recently. We have a new operator to implement.
<img width="1232" alt="image" src="https://github.com/user-attachments/assets/73ecd1ae-3bab-4645-8e80-afadac227893">

**Comment by chunhuanMeng** [comment]
we can close this issue
