### ISSUE TITLE
E2E test got scratch page issue with rolling driver

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#551]
### 🐛 Describe the bug

xpu  train AllenaiLongformerBase              
FATAL: Unexpected page fault from GPU at 0xff0000014c000000, ctx_id: 1 (CCS) type: 0 (NotPresent), level: 1 (PDE), access: 0 (Read), banned: 1, aborting.
FATAL: Unexpected page fault from GPU at 0xff0000014c000000, ctx_id: 1 (CCS) type: 0 (NotPresent), level: 1 (PDE), access: 0 (Read), banned: 1, aborting.
Abort was called at 287 line in file:
./shared/source/os_interface/linux/drm_neo.cpp
Run failed with return code:  -6

### Versions

Driver: 914.17
Bundle: 0.5.1
torch-xpu-ops: 01d4375a5bf6766fbdf0be2c1a3630105fc8b6a9
pytorch: 2f21c45513b13f238a18afaab2f98456399d76a3

**Comment by chuanqi129** [comment]
I remember it's a kernel bug, @fengyuan14 please help to assign this issue to the right person

**Comment by fengyuan14** [comment]
Looks not that issue. MaxPool2d is not ported in torch-xpu-ops. Anyway I will ask Sutong's help to take a look.

**Comment by fengyuan14** [comment]
As Sutong's comment, pengfei is working on the issue.

**Comment by Stonepia** [comment]
I'll take this.

**Comment by Stonepia** [comment]
This seems passed in PTv2.3 with latest oneDNN commit. Will test it with stock PT with latest oneDNN commit.
