### ISSUE TITLE
To investigate relocation error at linkage time and find a better solution when total bin size of libtorch_xpu.so is greater than 2GB.

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#586]
### 🚀 The feature, motivation and pitch

The existing solution: https://github.com/intel/torch-xpu-ops/pull/581
To split libtorch_xpu.so into multiple libraries,
1. libtorch_xpu.so, including operator level program. It is host only.
2. libtorch-xpu-ops-sycl-ker-partx.so, including kernel level program, both device code and host code.

**Comment by chuanqi129** [comment]
Will it target PT 2.5?

**Comment by fengyuan14** [comment]
We are following up the feature, 'device code compression', which will mitigate the panic significantly.
