### ISSUE TITLE
Case regression due to PyTorch uplift

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#614]
### 🐛 Describe the bug
Closed https://github.com/intel/torch-xpu-ops/issues/549, keep the rest of the issue here.

New failures occur when PyTorch uplifts.
Guilty commit should be between f053be2a97e1f6f9b2252cb800edd46f720af502 and d44c30e2f90d9ebe829875324f0ac662d04833a8.

 

- [x] test_compare_cpu_nn_functional_batch_norm_xpu_float16 
- [x]  test_compare_cpu_std_mean_xpu_bfloat16
- [x]  test_compare_cpu_var_mean_xpu_bfloat16

all within the threashold.

### Versions

Latest PyTorch.

**Comment by daisyden** [comment]
The two cases can pass with updated threshold.

![image](https://github.com/user-attachments/assets/9385f16b-d958-43a6-a267-3a3511f08b36)

![image](https://github.com/user-attachments/assets/bc12dab6-89a0-45d3-88d7-96c9d4ba98ac)

**Comment by xytintel** [comment]
The error of `test_compare_cpu_nn_functional_batch_norm_xpu_float16` is small.
![image](https://github.com/user-attachments/assets/7a213abf-5b4d-44d8-afc4-09940c0990a4)

**Comment by daisyden** [comment]
@yuchengliu1  please configure tolerance for these cases.

**Comment by yuchengliu1** [comment]
`test_compare_cpu_nn_functional_batch_norm_xpu_float16` pass in #749

**Comment by yuchengliu1** [comment]
"test_compare_cpu_nn_functional_batch_norm_xpu_float16",
 "test_compare_cpu_std_mean_xpu_bfloat16",
 "test_compare_cpu_var_mean_xpu_bfloat16",
pass in https://github.com/intel/torch-xpu-ops/pull/749
