### ISSUE TITLE
UT got failed with FP64 emulation feature

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#645]
### 🐛 Describe the bug

Details in https://github.com/mengfei25/torch-xpu-ops/actions/runs/10001966312/job/27646521195
Failed test cases:
pytest -sv third_party/torch-xpu-ops/test/xpu/extended/test_ops_xpu.py::TestCommonXPU::test_compare_cpu__refs_rsub_xpu_float16
pytest -sv third_party/torch-xpu-ops/test/xpu/test_nn_xpu.py::TestNNDeviceTypeXPU::test_grid_sample_large_xpu
pytest -sv third_party/torch-xpu-ops/test/xpu/test_nn_xpu.py::TestNNDeviceTypeXPU::test_variable_sequence_xpu_float16
pytest -sv third_party/torch-xpu-ops/test/xpu/test_tensor_creation_ops_xpu.py::TestTensorCreationXPU::test_float_to_int_conversion_finite_xpu_int64
pytest -sv third_party/torch-xpu-ops/test/xpu/test_reductions_xpu.py::TestReductionsXPU::test_all_any_vs_numpy_xpu_complex64
pytest -sv third_party/torch-xpu-ops/test/xpu/test_reductions_xpu.py::TestReductionsXPU::test_min_xpu_bool
pytest -sv third_party/torch-xpu-ops/test/xpu/test_indexing_xpu.py::TestIndexingXPU::test_index_put_accumulate_large_tensor_xpu
pytest -sv third_party/torch-xpu-ops/test/xpu/ test_dataloader.py

### Versions

Device: ARC
Driver: 914.32
Bundle: 0.5.3
PyTorch: bd12fbe65295fd59b73cfcf63eca32f30e5f15e5
Torch-xpu-ops: https://github.com/intel/torch-xpu-ops/pull/511

**Comment by chuanqi129** [comment]
It's not related with FP64

**Comment by daisyden** [comment]
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/extended/test_ops_xpu.py::TestCommonXPU::test_compare_cpu__refs_rsub_xpu_float16
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_nn_xpu.py::TestNNDeviceTypeXPU::test_grid_sample_large_xpu, also failed on MTL
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_nn_xpu.py::TestNNDeviceTypeXPU::test_variable_sequence_xpu_float16
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_tensor_creation_ops_xpu.py::TestTensorCreationXPU::test_float_to_int_conversion_finite_xpu_int64: also failed on MTL, GSD-9643
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_reductions_xpu.py::TestReductionsXPU::test_all_any_vs_numpy_xpu_complex64: Alaso failed on MTL
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_reductions_xpu.py::TestReductionsXPU::test_min_xpu_bool: also failed on MTL
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/test_indexing_xpu.py::TestIndexingXPU::test_index_put_accumulate_large_tensor_xpu: OOM also on MTL
- [ ] pytest -sv third_party/torch-xpu-ops/test/xpu/ test_dataloader.py
