### ISSUE TITLE
New case failure after PyTorch uplift: test_module_hooks.TestStateDictHooks.test_register_state_dict_post_hook

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#658]
### 🐛 Describe the bug

```
TypeError: TestStateDictHooks.test_register_state_dict_post_hook() missing 1 required positional argument: 'private'
```

To evaluate the case, if it is a device agnostic failure.

### Versions

Latest PyTorch.

**Comment by PenghuiCheng** [comment]
case is skiped in below version:
torch-xpu-ops:fb8e6e9ef0240523c32a856a45220fc5cb55012c
pytorch: e5560d10f4ee621b5952f61950761bac1d105afd

**Comment by daisyden** [comment]
This case is skipped in latest pytorch.

(gpu_ut) (base) penghuic@DUT1025PVC:~/stock_pytorch/third_party/torch-xpu-ops$ PYTORCH_TEST_WITH_SLOW=1 pytest -v test/xpu/test_modules_xpu.py -k "test_register_state_dict_post_hook" -s
======================================================================= test session starts =======================================================================
platform linux -- Python 3.10.14, pytest-7.3.2, pluggy-1.5.0 -- /home/penghuic/miniforge3/envs/gpu_ut/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/penghuic/stock_pytorch/third_party/torch-xpu-ops/.hypothesis/examples')
rootdir: /home/penghuic/stock_pytorch
configfile: pytest.ini
plugins: cpp-2.3.0, flakefinder-1.1.0, hypothesis-5.35.1, rerunfailures-14.0, xdoctest-1.1.0, xdist-3.3.1
collected 3605 items / 3605 deselected / 0 selected
