### ISSUE TITLE
[PageFault] `VectorizedElementwiseKernel` cause pagefault 

### ISSUE THREAD

**Issue by Stonepia** [intel/torch-xpu-ops#674]
### 🐛 Describe the bug

Affected total of 21 test:

test_fn_fwgrad_bwgrad_nn_functional_pairwise_distance_xpu_float64
test_backward_sgn_xpu_float32
test_forward_ad_sgn_xpu_float32
test_noncontiguous_samples_sgn_xpu_float32
test_variant_consistency_eager_sgn_xpu_float32
test_neg_view_sgn_xpu_float64
test_fn_fwgrad_bwgrad_sgn_xpu_float64
test_forward_mode_AD_sgn_xpu_float64
test_inplace_forward_mode_AD_sgn_xpu_float64
test_forward_mode_AD_sub_xpu_complex128
test_forward_mode_AD_sub_xpu_float64
test_inplace_forward_mode_AD_sub_xpu_complex128
test_inplace_forward_mode_AD_sub_xpu_float64
test_fn_fwgrad_bwgrad_abs_xpu_float64
test_fn_fwgrad_bwgrad_nn_functional_l1_loss_xpu_float64
test_forward_mode_AD_rsub_xpu_complex128
test_forward_mode_AD_rsub_xpu_float64
test_fn_fwgrad_bwgrad_nn_functional_smooth_l1_loss_xpu_float64
test_fn_fwgrad_bwgrad_nn_functional_softsign_xpu_float64
test_fn_fwgrad_bwgrad_special_i0e_xpu_float64
test_fn_fwgrad_bwgrad_special_i1e_xpu_float64

Run command:

```Bash
export DisableScratchPages=1 
export NEOReadDebugKeys=1

export PYTORCH_TEST_WITH_SLOW=1 

python -m pytest -v test_ops_fwd_gradients_xpu.py -k test_fn_fwgrad_bwgrad_abs_xpu_float64 
```
Use the following command for more detail:

```
export SYCL_PI_TRACE=-1

export ZE_SERIALIZE=2
export OverrideImmediateCmdListSynchronousMode=1
```

### Versions

PyTorch version: 2.5.0a0+gitae708e9
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.47+prerelease24.3.26-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.5.0a0+gitae708e9
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.5.0a0+gitae708e9           dev_0    <develop>

**Comment by fengyuan14** [comment]
Fixing: https://github.com/intel/torch-xpu-ops/pull/702, https://github.com/intel/torch-xpu-ops/pull/689
