### ISSUE TITLE
MTL: Reduction: Computation error in work group reduction on SLM when SIMD=8

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#698]
### 🐛 Describe the bug

It is possibly an issue of compiler software stack, SYCL compiler or IGC. The issue is filed for tracking. Will retrieve original logic if the issue is fixed.

### Versions

Latest PyTorch.

**Comment by chuanqi129** [comment]
@xytintel please help to double check whether we can close this issue

**Comment by Stonepia** [comment]
Close issue as already been fixed.
