### ISSUE TITLE
Implement Aten::_foreach_norm when `ord == inf`

### ISSUE THREAD

**Issue by chunhuanMeng** [intel/torch-xpu-ops#710]
### 🚀 The feature, motivation and pitch

For now ,when `ord == inf` ,it fallback to cpu, we should have the implementation when `ord == inf` to same as cuda.

**Comment by chunhuanMeng** [comment]
https://github.com/intel/torch-xpu-ops/pull/908

**Comment by xytintel** [comment]
PR Merged
