### ISSUE TITLE
AMP will be out of memory on MTL

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#752]
### 🐛 Describe the bug

Observed E2E performance on MTL, amp will be out of memory and machine will be disconnected.
reproduce
`
bash inductor_xpu_test.sh huggingface amp_bf16 inference performance xpu 0 static
`

### Versions

pytorch: 7d5462bfd6171467c0a6c23633732484cf85861e
torch-xpu-ops: 24a4557bcb140b9dffebc57e9d47e1849c4e9140

**Comment by Stonepia** [comment]
Close this issue as the OOM and machine disconnect be related to the Driver bug. Refer to internal GSD-10285 for the detail.
IPEX team is already WIP for the new driver test.
