### ISSUE TITLE
[Infrastructure] Align dtypesIfXPU of refs op with CUDA

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#768]
### 🐛 Describe the bug

Refs op will use the original op dtypes, we can also align the dtypesIfXPU of refs ops with cuda to avoid issues like the below. The two cases are skipped by cuda but not by torch-xpu-ops. 

- [ ] # NameError: name 'nanj' is not defined. Did you mean: 'nan'?

        "test_python_ref_executor__refs_logaddexp_executor_aten_xpu_complex128",
        "test_python_ref_executor__refs_logaddexp_executor_aten_xpu_complex64",

### Versions

latest version

**Comment by yuchengliu1** [comment]
These two cases does not run in current vision
