### ISSUE TITLE
[To evaluate] Issues of test_pooling_xpu.py

### ISSUE THREAD

**Issue by PenghuiCheng** [intel/torch-xpu-ops#771]
### 🚀 The feature, motivation and pitch

1. RuntimeError: "avg_pool3d_out_frame" not implemented for 'BFloat16'
cases:
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_pooling_bfloat16_xpu
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_pool_large_size_xpu_bfloat16

2. RuntimeError: "adaptive_max_pool3d_cpu" not implemented for 'Half'
cases:
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_AdaptiveMaxPool3d_indices_xpu_float16
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_max_pool_nan_inf_xpu_float16
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_adaptive_pooling_empty_output_size_xpu_float16
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_maxpool_indices_no_batch_dim_xpu_float16
nn/test_pooling_xpu.py::TestPoolingNNDeviceTypeXPU::test_pool_large_size_xpu_float16

**Comment by chuanqi129** [comment]
@chunhuanMeng does this issue target for PT2.5?

**Comment by chunhuanMeng** [comment]
> @chunhuanMeng does this issue target for PT2.5?

no, it's for PT2.6

**Comment by chunhuanMeng** [comment]
Cases above have been passed in the main branch ,suggest to close this issue.
