### ISSUE TITLE
Support XPU backend in 'toAccumulateType'

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#839]
### 🚀 The feature, motivation and pitch

There is lack of XPU support in of `toAccumulateType`.
https://github.com/pytorch/pytorch/blob/97c8a0739e6eadbf99bfdb21a999db735658d13b/aten/src/ATen/AccumulateType.cpp#L5-L16

**Comment by xytintel** [comment]
Merged in https://github.com/pytorch/pytorch/pull/134465
