### ISSUE TITLE
Pow operator complex32 type UT failure on Windows

### ISSUE THREAD

**Issue by Kanya-Mo** [intel/torch-xpu-ops#842]
### 🐛 Describe the bug

(Windows only) Pow operator gives incorrect result in UT test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_pow_xpu_float16.  
#798 is to fix this failure. However, additional overhead was introduced in type cast so we need to record this.  

The failure is related to the cast of complex half type in kernel. If we convert with opmath_t{}, other ops like log will also gives incorrect results. 

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/47cbc58452e74f70afb5e7f108ff8d7ecc329f21
pytorch: c8626a4e1f0553c8a9af32515555409d151a00c0

**Comment by Stonepia** [comment]
This is a bug due to the compiler. For internal user, please track with JIRA CMPLRLLVM-62734 .

**Comment by Stonepia** [comment]
tracked in https://github.com/intel/torch-xpu-ops/issues/1195
