### ISSUE TITLE
abs implementation for complex data type may have bug. 

### ISSUE THREAD

**Issue by etaf** [intel/torch-xpu-ops#88]
### 🐛 Describe the bug

The following script will get error `"le_xpu" not implemented for 'ComplexFloat'`, which is a fake error message.
```import torch
a = torch.tensor([3.+3.j], device="xpu")
b = torch.tensor([3.+3.j], device="xpu")
assert torch.isclose(a,b)
```

if we force fallback aten::abs to CPU by `export PYTORCH_XPU_FALLBACK_OP=abs`, then this case can pass.

### Versions

latset torch-xpu-ops: 62aa0ec62f051234faa425f236f8df0569ff622e

**Comment by xytintel** [comment]
Supplement missing logic for abs：https://github.com/intel/torch-xpu-ops/pull/89

**Comment by etaf** [comment]
verified.
