### ISSUE TITLE
[FP16]For OPTForCausalLM train on stock pytorch, aten::add cost time on pvc-1100 worse than A100 * ratio

### ISSUE THREAD

**Issue by xiaowangintel** [intel/torch-xpu-ops#884]
### 🐛 Describe the bug

For more details, please refer to https://jira.devtools.intel.com/browse/PYTORCHDGQ-5162?filter=-2.

### Versions

pytorch commit:03480213dea1f60f6d12e7348904d2f3ef7314d0
torch-xpu-ops commit:718bc42c667539977e5eadb11ea4dec602544bf2
driver : hotfix_agama-ci-devel-881.19
pti : l_intel-pti-dev_p_0.9.0.38_offline.sh
basekit : l_BaseKit_p_2024.2.1.100_offline.sh

**Comment by fengyuan14** [comment]
We have apple-apple implementation as PyTorch CUDA. Two performance limitation of HW,
1. Instruction bound on PVC. When tensor has data type with less than 32 bits, need increase payload of each instruction to feed memory well.
2. Memory/cache efficiency of broadcast case. Efficiency of reusing data in LLC is not good as A100.
