### ISSUE TITLE
aten::_assert_async.msg is required in multinomial

### ISSUE THREAD

**Issue by ZhiweiYan-96** [intel/torch-xpu-ops#907]
### 🚀 The feature, motivation and pitch

The issue is found in codegen PR, where `aten::_assert_async.msg` is called in op multinomial. It affects the uts in `extended/test_ops_xpu.py`
```python
    "test_operator_multinomial_xpu_float32",
    "test_view_replay_multinomial_xpu_float32"
```

**Comment by xytintel** [comment]
Relevant PR: https://github.com/intel/torch-xpu-ops/pull/955, merged
