### ISSUE TITLE
[ARC Windows] UT failures

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#910]
### 🐛 Describe the bug

Failures on ARC windows, total 2127,FP64 related issue: 1910, others: 217
- [ ] AssertionError: 'Assertion `cur_target >= 0 && cur_target < n_classes` failed' not found in 'PYTORCH_API_USAGE
- [ ] AssertionError: "Kernel\ is\ incompatible\ with\ all\ devices\ in\ devs" does not match "Required aspect fp64 is not supported on the device"
- [ ] AssertionError: "not implemented for" does not match "Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)"
- [ ] AssertionError: RuntimeError not raised
- [ ] AssertionError: Scalars are not close!
- [ ] AssertionError: Tensor-likes are not close!
- [ ] AssertionError: Tensor-likes are not equal!
- [ ] Exception: Caused by sample input at index
- [ ] RuntimeError: Caught RuntimeError in DataLoader worker process 1.
- [ ] RuntimeError: Comparing
- [ ] RuntimeError: could not create a primitive descriptor for a convolution forward propagation primitive
- [ ] RuntimeError: could not create a primitive descriptor for a deconvolution forward propagation primitive
- [ ] RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] RuntimeError: Kernel is incompatible with all devices in devs
- [ ] RuntimeError: Loader error
- [ ] RuntimeError: Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
- [ ] RuntimeError: Ninja is required to load C++ extensions
- [ ] RuntimeError: Required aspect fp64 is not supported on the device
- [ ] RuntimeError: Worker error
- [ ] RuntimeError: XPU out of memory, please use `empty_cache` to release all unoccupied cached memory.
- [ ] AssertionError: Scalars are not close!
- [ ] Exception: Caused by sample input at index

### Versions

torch-xpu-ops: release/2.5

**Comment by chuanqi129** [comment]
@min-jean-cho could you please double check whether those issues are expected?

**Comment by chuanqi129** [comment]
@PenghuiCheng please share the linux ARC UT test results as reference

**Comment by PenghuiCheng** [comment]
> @PenghuiCheng please share the linux ARC UT test results as reference

attached. arc_log.txt is UT of test/xpu, and arc_extended_log.txt is UT of test/xpu/extended.
[arc_log.txt](https://github.com/user-attachments/files/17037845/arc_log.txt)
[arc_extended_log.txt](https://github.com/user-attachments/files/17037846/arc_extended_log.txt)

**Comment by chuanqi129** [comment]
Hi @min-jean-cho, any update on this issue?

**Comment by Stonepia** [comment]
Close as this is out-dated. We will create a new issue for new round test.
