### ISSUE TITLE
[ARC E2E] Torchbench accuracy failed

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#912]
### 🐛 Describe the bug

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Category | Model | Accuracy
-- | -- | --
torchbench_amp_bf16_training | basic_gnn_edgecnn | eager_two_runs_differ
torchbench_amp_bf16_training | densenet121 | fail_accuracy
torchbench_bfloat16_training | densenet121 | fail_accuracy
torchbench_float16_training | fastNLP_Bert | fail_accuracy
torchbench_bfloat16_training | functorch_maml_omniglot | fail_accuracy
torchbench_amp_bf16_training | hf_Reformer | fail_accuracy
torchbench_amp_fp16_training | hf_Reformer | fail_accuracy
torchbench_bfloat16_training | hf_Reformer | eager_two_runs_differ
torchbench_float16_training | hf_Reformer | fail_accuracy
torchbench_amp_bf16_training | hf_Roberta_base | eager_2nd_run_fail
torchbench_amp_fp16_training | hf_Roberta_base | eager_2nd_run_fail
torchbench_bfloat16_training | hf_Roberta_base | fail_accuracy
torchbench_float16_training | hf_Roberta_base | fail_accuracy
torchbench_float32_training | hf_Roberta_base | eager_2nd_run_fail
torchbench_amp_bf16_training | hf_Whisper | fail_accuracy
torchbench_amp_fp16_training | hf_Whisper | fail_accuracy
torchbench_float32_training | maml_omniglot | fail_accuracy
torchbench_bfloat16_inference | pyhpc_equation_of_state | fail_accuracy
torchbench_float16_inference | pyhpc_equation_of_state | fail_accuracy
torchbench_amp_fp16_training | pytorch_CycleGAN_and_pix2pix | fail_accuracy
torchbench_float16_training | pytorch_CycleGAN_and_pix2pix | fail_accuracy
torchbench_float16_inference | sam | fail_accuracy
torchbench_amp_bf16_training | timm_regnet | fail_accuracy
torchbench_float32_training | timm_regnet | eager_two_runs_differ

</body>

</html>

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/7e3d00acea9f0d3728048a5b2743de20d55c64ba
pytorch: 0d1d69fd25fdc096763bfe85f4d379e27ea1c9f8
device: ARC 24.04
driver: 24.31.30508.7

**Comment by mengfei25** [comment]
Compared with 22.04

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Category | Model | Ubuntu 24.04 | Ubuntu 22.04
-- | -- | -- | --
torchbench_amp_bf16_training | densenet121 | fail_accuracy | pass
torchbench_bfloat16_training | densenet121 | fail_accuracy | pass
torchbench_float32_inference | hf_T5 | pass | eager_fail_to_run
torchbench_float32_inference | vision_maskrcnn | fail_accuracy | pass
torchbench_float32_training | basic_gnn_edgecnn | pass | eager_two_runs_differ



</body>

</html>

**Comment by Stonepia** [comment]
We will mainly target to Ubuntu24.10, the E2E accuracy issue will be closed.
