### ISSUE TITLE
[ARC E2E] Timm models accuracy failed

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#913]
### 🐛 Describe the bug

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Category | Model | Accuracy
-- | -- | --
timm_models_amp_bf16_training | botnet26t_256 | fail_accuracy
timm_models_amp_fp16_training | botnet26t_256 | fail_accuracy
timm_models_bfloat16_training | botnet26t_256 | fail_accuracy
timm_models_amp_bf16_training | convmixer_768_32 | fail_accuracy
timm_models_bfloat16_training | convmixer_768_32 | fail_accuracy
timm_models_float32_training | convnext_base | fail_accuracy
timm_models_amp_bf16_training | cspdarknet53 | fail_accuracy
timm_models_bfloat16_training | cspdarknet53 | fail_accuracy
timm_models_amp_bf16_training | eca_botnext26ts_256 | fail_accuracy
timm_models_bfloat16_training | eca_botnext26ts_256 | fail_accuracy
timm_models_bfloat16_training | eca_halonext26ts | fail_accuracy
timm_models_bfloat16_training | fbnetv3_b | fail_accuracy
timm_models_amp_bf16_training | gluon_inception_v3 | fail_accuracy
timm_models_bfloat16_training | gluon_inception_v3 | fail_accuracy
timm_models_amp_bf16_training | lcnet_050 | fail_accuracy
timm_models_bfloat16_training | lcnet_050 | fail_accuracy
timm_models_amp_bf16_training | levit_128 | fail_accuracy
timm_models_bfloat16_training | levit_128 | fail_accuracy
timm_models_amp_bf16_training | mixer_b16_224 | fail_accuracy
timm_models_bfloat16_training | mixer_b16_224 | fail_accuracy
timm_models_amp_bf16_training | mobilenetv2_100 | fail_accuracy
timm_models_amp_fp16_training | mobilenetv2_100 | fail_accuracy
timm_models_bfloat16_training | mobilenetv2_100 | fail_accuracy
timm_models_bfloat16_training | mobilevit_s | eager_two_runs_differ
timm_models_float16_training | poolformer_m36 | fail_accuracy
timm_models_amp_bf16_inference | res2net50_14w_8s | fail_accuracy
timm_models_amp_bf16_training | res2net50_14w_8s | fail_accuracy
timm_models_amp_fp16_inference | res2net50_14w_8s | fail_accuracy
timm_models_amp_fp16_training | res2net50_14w_8s | fail_accuracy
timm_models_bfloat16_inference | res2net50_14w_8s | fail_accuracy
timm_models_bfloat16_training | res2net50_14w_8s | fail_accuracy
timm_models_float16_inference | res2net50_14w_8s | fail_accuracy
timm_models_float16_training | res2net50_14w_8s | fail_accuracy
timm_models_float32_inference | res2net50_14w_8s | fail_accuracy
timm_models_float32_training | res2net50_14w_8s | fail_accuracy
timm_models_amp_bf16_training | resnest101e | fail_accuracy
timm_models_bfloat16_training | resnest101e | fail_accuracy
timm_models_amp_bf16_training | rexnet_100 | fail_accuracy
timm_models_bfloat16_training | rexnet_100 | fail_accuracy
timm_models_amp_bf16_training | sebotnet33ts_256 | fail_accuracy
timm_models_amp_fp16_training | sebotnet33ts_256 | fail_accuracy
timm_models_bfloat16_training | sebotnet33ts_256 | fail_accuracy
timm_models_float16_training | sebotnet33ts_256 | fail_accuracy
timm_models_amp_bf16_training | swin_base_patch4_window7_224 | fail_accuracy
timm_models_bfloat16_training | swin_base_patch4_window7_224 | fail_accuracy
timm_models_amp_fp16_training | tf_efficientnet_b0 | fail_accuracy
timm_models_amp_bf16_training | tinynet_a | fail_accuracy
timm_models_bfloat16_training | tinynet_a | fail_accuracy
timm_models_amp_fp16_training | tnt_s_patch16_224 | eager_two_runs_differ
timm_models_bfloat16_training | tnt_s_patch16_224 | eager_two_runs_differ
timm_models_float32_training | tnt_s_patch16_224 | eager_two_runs_differ

</body>

</html>

### Versions

torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/7e3d00acea9f0d3728048a5b2743de20d55c64ba
pytorch: 0d1d69fd25fdc096763bfe85f4d379e27ea1c9f8
device: ARC 24.04
driver: 24.31.30508.7

**Comment by chuanqi129** [comment]
@mengfei25 please compare this result with Ubuntu 22.04

**Comment by mengfei25** [comment]
Compared with 22.04

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mengfeil/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Category | Model | Ubuntu 24.04 | Ubuntu 22.04
-- | -- | -- | --
timm_models_amp_bf16_inference | res2net50_14w_8s | fail_accuracy | pass
timm_models_amp_bf16_training | coat_lite_mini | pass | eager_two_runs_differ
timm_models_amp_bf16_training | convit_base | pass | eager_two_runs_differ
timm_models_amp_bf16_training | convnext_base | pass | eager_two_runs_differ
timm_models_amp_bf16_training | jx_nest_base | pass | eager_two_runs_differ
timm_models_amp_bf16_training | mobilevit_s | pass | eager_two_runs_differ
timm_models_amp_bf16_training | res2net50_14w_8s | fail_accuracy | pass
timm_models_amp_fp16_inference | res2net50_14w_8s | fail_accuracy | pass
timm_models_amp_fp16_training | coat_lite_mini | pass | eager_two_runs_differ
timm_models_amp_fp16_training | convit_base | pass | eager_two_runs_differ
timm_models_amp_fp16_training | convnext_base | pass | eager_two_runs_differ
timm_models_amp_fp16_training | jx_nest_base | pass | eager_two_runs_differ
timm_models_amp_fp16_training | mobilevit_s | pass | eager_two_runs_differ
timm_models_amp_fp16_training | res2net50_14w_8s | fail_accuracy | pass
timm_models_amp_fp16_training | twins_pcpvt_base | pass | eager_two_runs_differ
timm_models_bfloat16_inference | res2net50_14w_8s | fail_accuracy | pass
timm_models_bfloat16_training | jx_nest_base | pass | eager_two_runs_differ
timm_models_bfloat16_training | mobilevit_s | eager_two_runs_differ | pass
timm_models_bfloat16_training | res2net50_14w_8s | fail_accuracy | pass
timm_models_bfloat16_training | volo_d1_224 | pass | fail_accuracy
timm_models_float16_inference | res2net50_14w_8s | fail_accuracy | pass
timm_models_float16_training | coat_lite_mini | pass | eager_two_runs_differ
timm_models_float16_training | convit_base | pass | eager_two_runs_differ
timm_models_float16_training | jx_nest_base | pass | eager_two_runs_differ
timm_models_float16_training | res2net50_14w_8s | fail_accuracy | pass
timm_models_float16_training | swin_base_patch4_window7_224 | pass | eager_two_runs_differ
timm_models_float16_training | twins_pcpvt_base | pass | eager_two_runs_differ
timm_models_float32_inference | res2net50_14w_8s | fail_accuracy | pass
timm_models_float32_training | res2net50_14w_8s | fail_accuracy | pass



</body>

</html>

**Comment by riverliuintel** [comment]
Clean issues. Use PT2.6 Ubuntu 24.10 and submit new issues.
