### ISSUE TITLE
Unittest: New failures after PyTorch uplift

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#922]
### 🐛 Describe the bug

- [ ] #956
- [ ] TestMetaXPU::test_dispatch_meta_outplace_unique_consecutive_xpu_bfloat16 
- [x] TestMetaXPU::test_dispatch_symbolic_meta_outplace_isin_xpu_bfloat16
- [ ] TestMetaXPU::test_dispatch_symbolic_meta_outplace_unique_consecutive_xpu_bfloat16 
- [x] TestMetaXPU::test_meta_outplace_isin_xpu_bfloat16 
- [ ] TestMetaXPU::test_meta_outplace_unique_consecutive_xpu_bfloat16 
- [x] TestCommonXPU::test_compare_cpu_isin_xpu_bfloat16
- [ ] TestCommonXPU::test_compare_cpu_unique_consecutive_xpu_bfloat16 
- [x] TestCommonXPU::test_dtypes_isin_xpu

### Versions

Latest PyTorch

**Comment by daisyden** [comment]
isin cases are passed on pytorch 41977a05314bbf537e1c5d6cf5916a368d1907d9 and torch-xpu-ops 999094bc948b3afd21162784dead1e765c60a376.
Pr for unique: https://github.com/intel/torch-xpu-ops/pull/963

**Comment by chunhuanMeng** [comment]
cases above all passed， suggest to close this issue.
